=== strategoslevel3/StrategosMekBay/MekHQ-0.51.00/data/forcegenerator/faction_rules/formationRulesetSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
# MegaMek Data (C) 2025 by The MegaMek Team is licensed under CC BY-NC-SA 4.0.
# To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek Data was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:attributeGroup name="predicateAttributeGroup">
        <xs:attribute name="ifUnitType" type="xs:string" />
        <xs:attribute name="ifWeightClass" type="xs:string" />
        <xs:attribute name="ifRating" type="xs:string" />
        <xs:attribute name="ifFormation" type="xs:string" />
        <xs:attribute name="ifRole" type="xs:string" />
        <xs:attribute name="ifMotive" type="xs:string" />
        <xs:attribute name="ifAugmented" type="xs:boolean" />
        <xs:attribute name="ifDateBetween" type="xs:string" />
        <xs:attribute name="ifTopLevel" type="xs:boolean" />
        <xs:attribute name="ifName" type="xs:string" />
        <xs:attribute name="ifFaction" type="xs:string" />
        <xs:attribute name="ifFlags" type="xs:string" />
        <xs:attribute name="ifIndex" type="xs:string" />
    </xs:attributeGroup>

    <xs:attributeGroup name="assertionAttributeGroup">
        <xs:attribute name="unitType" type="xs:string" />
        <xs:attribute name="weightClass" type="xs:string" />
        <xs:attribute name="rating" type="xs:string" />
        <xs:attribute name="formation" type="xs:string" />
        <xs:attribute name="role" type="xs:string" />
        <xs:attribute name="motive" type="xs:string" />
        <xs:attribute name="augmented" type="xs:boolean" />
        <xs:attribute name="chassis" type="xs:string" />
        <xs:attribute name="model" type="xs:string" />
        <xs:attribute name="variant" type="xs:string" />
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="fluffName" type="xs:string" />
        <xs:attribute name="faction" type="xs:string" />
        <xs:attribute name="flags" type="xs:string" />
    </xs:attributeGroup>

    <xs:group name="ruleGroup">
        <xs:choice>
            <xs:element name="weightClass" type="optionGroupType" />
            <xs:element name="unitType" type="optionGroupType" />
            <xs:element name="chassis" type="optionGroupType" />
            <xs:element name="variant" type="optionGroupType" />
            <xs:element name="motive" type="optionGroupType" />
            <xs:element name="formation" type="optionGroupType" />
            <xs:element name="role" type="optionGroupType" />
            <xs:element name="flags" type="optionGroupType" />
            <xs:element name="changeEschelon" type="optionGroupType" />
        </xs:choice>
    </xs:group>

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="defaults" />
                <xs:element minOccurs="0" maxOccurs="1" ref="customRanks" />
                <xs:element minOccurs="0" maxOccurs="1" ref="toc" />
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="force" />
            </xs:sequence>
            <xs:attribute name="faction" type="xs:string" />
            <xs:attribute name="parent" type="xs:string" />
            <xs:attribute name="ratingSystem">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="IS|SL|CLAN|ROS" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="defaults">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="unitType">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="echelon">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rankSystem">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rating">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="toc">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" name="unitType" type="tocType" />
                <xs:element minOccurs="0" maxOccurs="1" name="echelon" type="tocType" />
                <xs:element minOccurs="0" maxOccurs="1" name="rating" type="tocType" />
                <xs:element minOccurs="0" maxOccurs="1" name="flags" type="tocType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="customRanks">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="base" type="xs:string" />
                <xs:element maxOccurs="unbounded" name="rank">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value=".+:.+" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="force">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" minOccurs="0"
                            maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="weightTarget" minOccurs="0"
                            maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="unitType" type="xs:string" />
                                <xs:attribute name="spread" type="xs:decimal" />
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="co" type="commanderType"
                            maxOccurs="unbounded" />
                <xs:element name="xo" type="commanderType"
                            minOccurs="0" maxOccurs="unbounded" />
                <xs:group ref="ruleGroup"
                          minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="ruleGroup" type="ruleGroupType"
                            minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="subforces" type="subforcesType"
                            minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="attachedForces"
                            type="subforcesType"
                            minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>

            <xs:attribute name="echelon" type="xs:string" use="required" />
            <xs:attribute name="eschName" type="xs:string" />
            <xs:attributeGroup ref="predicateAttributeGroup" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tocType">
        <xs:sequence>
            <xs:element name="option" type="tocOptionType"
                        maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tocOptionType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="ifEschelon" type="xs:string" />
                <xs:attributeGroup ref="predicateAttributeGroup" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="commanderType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="position" type="xs:integer" />
                <xs:attribute name="title" type="xs:string" />
                <xs:attribute name="unitType" type="xs:string" />
                <xs:attributeGroup ref="predicateAttributeGroup" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="ruleGroupType">
        <xs:sequence>
            <xs:group ref="ruleGroup" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="optionGroupType">
        <xs:sequence>
            <xs:element name="option" type="optionType"
                        maxOccurs="unbounded" />
        </xs:sequence>

        <xs:attributeGroup ref="predicateAttributeGroup" />
    </xs:complexType>

    <xs:complexType name="optionType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <!-- Deprecated alias for ifDateBetween (predicateAttributeGroup); kept for backwards compatibility. -->
                <xs:attribute name="ifYearBetween" type="xs:string" />
                <xs:attribute name="weight" type="xs:integer"
                              default="1" />
                <xs:attribute name="num" type="xs:integer" />
                <xs:attributeGroup ref="predicateAttributeGroup" />
                <xs:attributeGroup ref="assertionAttributeGroup" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="subforcesType">
        <xs:choice>
            <xs:element name="asFaction" type="xs:string" />
            <xs:element name="asParent" type="xs:string" />
            <xs:choice maxOccurs="unbounded">
                <xs:element name="subforce" type="subforceType" />
                <xs:element name="subforceOption"
                            type="subforceOptionType" />
            </xs:choice>
        </xs:choice>

        <xs:attributeGroup ref="predicateAttributeGroup" />
        <xs:attribute name="generate" type="generateType" />
    </xs:complexType>

    <xs:complexType name="subforceType">
        <xs:simpleContent>
            <xs:extension base="eschelonDefinition">
                <xs:attributeGroup ref="predicateAttributeGroup" />
                <xs:attributeGroup ref="assertionAttributeGroup" />
                <xs:attribute name="num" type="xs:integer" default="1" />
                <xs:attribute name="generate" type="generateType" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="generateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="model" />
            <xs:enumeration value="chassis" />
            <xs:enumeration value="group" />
            <xs:enumeration value="unit" />
            <xs:enumeration value="" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="eschelonDefinition">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]+|%[A-Z_]+%)[+-^]?" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="subforceOptionType">
        <xs:sequence>
            <xs:element name="option" type="optionType"
                        maxOccurs="unbounded" />
        </xs:sequence>

        <xs:attributeGroup ref="predicateAttributeGroup" />
        <xs:attribute name="generate" type="generateType" />
    </xs:complexType>

</xs:schema>

=== strategoslevel3/StrategosMekBay/MekHQ-0.51.00/data/forcegenerator/faction_rules/CWIE.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
# MegaMek Data (C) 2025 by The MegaMek Team is licensed under CC BY-NC-SA 4.0.
# To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek Data was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
-->
<ruleset faction="CWIE" parent="CW" ratingSystem="CLAN"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

    <defaults>
        <echelon>%CLUSTER%</echelon>
        <rankSystem>%RANK_CLAN%</rankSystem>
        <rating>FL</rating>
    </defaults>

    <!--Cluster composition is taken from the Clan Wolf sourcebook. FM:CC
    reflects a touman severely weakened by the Refusal War and the
    split between the Crusader Wolves and the Warden exiles.-->

    <toc>
        <unitType>
            <option ifDateBetween="3060,3084">null,Mek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter,Warship,Dropship,Jumpship</option>
            <option ifDateBetween="2870,">null,Mek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter,Warship,Dropship,Jumpship</option>
            <option ifDateBetween=",2869">null,Mek,Tank,VTOL,Infantry,AeroSpaceFighter,Conventional Fighter,Warship,Dropship,Jumpship</option>
        </unitType>

        <echelon>
            <option ifUnitType="">%TOUMAN%,%GALAXY%,%CLUSTER%</option>
            <option ifUnitType="Warship">%CLUSTER%</option>
            <option ifUnitType="Jumpship|Dropship">%STAR%</option>
            <option ifUnitType="Mek">%TRINARY%^,%TRINARY%,%BINARY%^,%BINARY%,%STAR%^,%STAR%</option>
            <option>%TRINARY%,%BINARY%,%STAR%</option>
        </echelon>

        <rating>
            <option ifUnitType="Tank|VTOL">SL:Second Line,PG:Garrison,Sol:Solahma</option>
            <option ifUnitType="Infantry" ifDateBetween="2900,">PG:Garrison,Sol:Solahma</option>
            <option ifUnitType="Infantry">SL:Second Line,PG:Garrison,Sol:Solahma</option>
            <option ifEschelon="%TOUMAN%"></option>
            <option ifDateBetween="3066," ifEschelon="%GALAXY%">FL:Front Line,SL:Second Line,Sol:Solahma</option>
            <option ifEschelon="%GALAXY%">FL:Front Line,SL:Second Line</option>
            <option ifEschelon="%CLUSTER%" ifDateBetween=",3065">Keshik,FL:Front Line,SL:Second Line,PG:Garrison</option>
            <option>Keshik,FL:Front Line,SL:Second Line,PG:Garrison,Sol:Solahma</option>
        </rating>
    </toc>

    <force echelon="%TOUMAN%" eschName="Touman">
        <co>%KHAN%</co>
        <xo>%SAKHAN%</xo>

        <subforces>
            <subforce name="Alpha Galaxy" rating="FL"
                      role="command">%GALAXY%
            </subforce>
            <subforce name="Beta Galaxy" rating="FL">%GALAXY%</subforce>
            <subforce name="Omega Galaxy" rating="SL">%GALAXY%</subforce>
        </subforces>

        <attachedForces>
            <subforce unitType="Warship">%CLUSTER%</subforce>
        </attachedForces>
    </force>

    <force echelon="%CLUSTER%" eschName="Fleet" ifUnitType="Warship">
        <name>Naval Reserve</name>
        <co>%GALAXY_CMDR%</co>

        <subforces>
            <subforce role="command" fluffName="CWS Werewolf"
                      ifDateBetween=",3077"
                      chassis="McKenna Battleship">%ELEMENT%
            </subforce>
            <subforce fluffName="CWS Ulric Kerensky"
                      ifDateBetween=",3074"
                      chassis="Cameron Battlecruiser">%ELEMENT%
            </subforce>
            <subforce fluffName="CWS Implacable"
                      ifDateBetween=",3075"
                      chassis="Black Lion II Battlecruiser">%ELEMENT%
            </subforce>
            <subforce fluffName="CWS Full Moon"
                      ifDateBetween=",3120"
                      chassis="Potemkin Troop Cruiser">%ELEMENT%
            </subforce>
            <subforce fluffName="CWS Valiant"
                      ifDateBetween=",3072"
                      chassis="Vincent Corvette">%ELEMENT%
            </subforce>
            <subforce fluffName="CWS Killing Blow"
                      ifDateBetween=",3072"
                      chassis="Vincent Corvette">%ELEMENT%
            </subforce>
            <subforce fluffName="CWS Jade Wolf" ifDateBetween="3062,3072"
                      chassis="Aegis Heavy Cruiser">%ELEMENT%
            </subforce>
            <subforce fluffName="CWS Black Paw" ifDateBetween="3062,3072"
                      chassis="Aegis Heavy Cruiser">%ELEMENT%
            </subforce>
        </subforces>
    </force>

    <!--Override to change PGC name-->

    <force echelon="%CLUSTER%" eschName="Cluster" ifRating="PG">
        <name>Wolf Guardians Cluster</name>
        <co>%STAR_COL%</co>

        <weightClass>
            <option weight="2">H</option>
            <option weight="2">M</option>
            <option weight="1">L</option>
        </weightClass>

        <subforces>
            <asParent />
        </subforces>
    </force>

    <force echelon="%STAR%" eschName="Star" ifAugmented="0" ifUnitType="Mek|ProtoMek">
        <name>{phonetic} {name:parent} Star</name>
        <co>%STAR_CMDR%</co>

        <weightClass>
            <option weight="2">H</option>
            <option weight="2">M</option>
            <option weight="1">L</option>
            <option ifRole="command" weight="1">H</option>
        </weightClass>

        <!--ProtoMeks appear on the FM:U RATs but not FM:3085, indicating
        the exiles abandoned their use during or after the Jihad.-->

        <unitType ifUnitType="Mek" ifRole="!command"
                  ifDateBetween="3060,3084" ifTopLevel="0">
            <option weight="9" />
            <option weight="3" ifDateBetween="3070," />
            <option ifRating="FL|SL">ProtoMek</option>
        </unitType>

        <ruleGroup>
            <formation ifIndex="0">
                <option weight="30" ifWeightClass="H|A">Battle</option>
                <option weight="12" ifWeightClass="H|A">Heavy Battle</option>
                <option weight="20" ifWeightClass="M">Medium Battle</option>
                <option weight="20" ifWeightClass="L">Light Battle</option>
                <option weight="12" ifWeightClass="H|A">Assault</option>
                <option weight="8" ifWeightClass="L|M|H">Striker/Cavalry</option>
                <option weight="4" ifWeightClass="H|A">Heavy Striker/Cavalry</option>
                <option weight="4" ifWeightClass="L">Light Striker/Cavalry</option>
                <option weight="1" ifWeightClass="L|M|H">Pursuit</option>
                <option weight="1" role="+urban">Urban</option>
            </formation>

            <formation ifIndex="!0">
                <option weight="20">Fire</option>
                <option weight="3">Fire Support</option>
                <option weight="2" ifWeightClass="H|A">Direct Fire</option>
                <option weight="2" ifWeightClass="L|M">Light Fire</option>
                <option weight="1" role="+anti_aircraft">Anti-Air</option>
                <option weight="24" ifWeightClass="H|A">Battle</option>
                <option weight="6" ifIndex="0,1">Battle</option>
                <option weight="12" ifWeightClass="H|A">Heavy Battle</option>
                <option weight="20" ifWeightClass="M">Medium Battle</option>
                <option weight="20" ifWeightClass="L">Light Battle</option>
                <option weight="6" ifWeightClass="H|A">Assault</option>
                <option weight="4" ifWeightClass="L|M|H">Striker/Cavalry</option>
                <option weight="4" ifWeightClass="H|A">Heavy Striker/Cavalry</option>
                <option weight="2" ifWeightClass="L">Light Striker/Cavalry</option>
                <option weight="1" ifWeightClass="L|M|H">Pursuit</option>
                <option weight="1" ifWeightClass="L|M|H">Ranger</option>
                <option weight="1" ifWeightClass="L|M|H">Probe</option>
                <option weight="1" ifWeightClass="L|M|H">Sweep</option>
                <option weight="1" role="+urban">Urban</option>
                <option weight="24" ifWeightClass="L|M" role="+recon">Recon</option>
                <option weight="8" ifWeightClass="H" role="+recon">Heavy Recon</option>
                <option weight="6" ifWeightClass="L" role="+recon">Light Recon</option>
            </formation>
        </ruleGroup>

        <subforces ifUnitType="Mek">
            <asParent />
        </subforces>
        <subforces ifUnitType="ProtoMek">
            <subforce generate="" num="5">%POINT%</subforce>
        </subforces>
    </force>
</ruleset>
